src/MyMovieCollection.Presentation/Models/ErrorViewModel.cs
namespace MyMovieCollection.Presentation.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/MyMovieCollection.Presentation/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyMovieCollection.Presentation.Models;

namespace MyMovieCollection.Presentation.Controllers;

[AllowAnonymous]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [Authorize]
    [Route("/Home")]
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Main()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/MyMovieCollection.Presentation/Controllers/IdentityController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyMovieCollection.Core.Models;
using MyMovieCollection.Core.Repositories;
using MyMovieCollectionю.Presentation.Dtos;

namespace MyMovieCollection.Presentation.Controllers;

[AllowAnonymous]
[Route("/[action]")]
public class IdentityController : Controller
{
    private readonly IUserRepository repository;

    public IdentityController(IUserRepository repository)
    {
        this.repository = repository;
    }

    [HttpGet]
    public IActionResult Login() => base.View();

    [HttpPost]
    public async Task<IActionResult> Login([FromForm] UserDto userDto)
    {
        var user = await repository.GetByLoginAndPassword(userDto.Login, userDto.Password);

        if (user is null) return BadRequest("Incorrect Login or Password!");

        var claims = new Claim[]
        {
            new("UserId", user.Id.ToString()),
            new(ClaimTypes.Name, user.Login!),
            new(ClaimTypes.Email, user.Email!),
        };

        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        await base.HttpContext.SignInAsync(
            scheme: CookieAuthenticationDefaults.AuthenticationScheme,
            principal: new ClaimsPrincipal(claimsIdentity)
        );

        return string.IsNullOrWhiteSpace(userDto.ReturnUrl)
            ? base.RedirectToAction(controllerName: "Home", actionName: "Index")
            : base.RedirectPermanent(userDto.ReturnUrl);

    }

    [HttpGet]
    public IActionResult Signup() => base.View();

    [HttpPost]
    public async Task<IActionResult> Signup([FromForm] UserDto userDto)
    {
        var newUser = new User()
        {
            Email = userDto.Email,
            Login = userDto.Login,
            Password = userDto.Password,
            PhoneNumber = userDto.PhoneNumber,
        };
        await repository.CreateAsync(newUser);

        return base.RedirectToAction("Login");
    }

    [HttpGet]
    [Authorize]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

        return RedirectToAction(controllerName: "Home", actionName: "Main");
    }
}

src/MyMovieCollection.Presentation/Controllers/MovieController.cs
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyMovieCollection.Core.Models;
using MyMovieCollection.Core.Repositories;
using MyMovieCollectionю.Presentation.Dtos;

namespace MyMovieCollection.Presentation.Controllers;

[Authorize]
public class MovieController : Controller
{
    private readonly IMovieRepository repository;

    public MovieController(IMovieRepository repository)
    {
        this.repository = repository;
    }

    [HttpGet] 
    [ActionName("Movies")]
    [Route("/Movies")]
    public async Task<IActionResult> GetAll()
    {
        var movies = await repository.GetAllAsync();
        return View(movies);
    }

    [HttpGet]
    [ActionName("About")]
    [Route("/Movie")]
    public async Task<IActionResult> GetById(int id)
    {
        var movie = await repository.GetByIdAsync(id);

        if (movie is null) return NotFound($"Movie with id {id} doesn't exist");

        return View(movie);
    }
}

src/MyMovieCollection.Presentation/Controllers/UserController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyMovieCollection.Core.Models;
using MyMovieCollection.Core.Repositories;
using MyMovieCollectionю.Presentation.Dtos;

namespace MyMovieCollection.Presentation.Controllers;

[Authorize]
[Route("/[action]")]
public class UserController : Controller
{
    private readonly IUserRepository repository;

    public UserController(IUserRepository repository)
    {
        this.repository = repository;
    }

    [HttpGet]
    public async Task<IActionResult> Profile() 
    {
        var id = int.Parse(User.FindFirstValue("UserId")!);
        var user = await repository.GetByIdAsync(id);
        return base.View(user);
    }   

}

src/MyMovieCollection.Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4"></h1>
</div>

src/MyMovieCollection.Presentation/Views/Home/Main.cshtml
@{
    ViewData["Title"] = "Main Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To My Movie Collection</h1>
</div>

src/MyMovieCollection.Presentation/Views/Movie/About.cshtml
@model Movie

@{
    ViewData["Title"] = $"About '{Model.Title}'";
}

<style>
    h1 {
        text-align: center;
    }

    h1 {
        font-size: 60px;
    }

    img {
        border-radius: 10px;
        width: 300px;
        height: 500px;
    }

    span,
    h1 {
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    .title {
        font-size: 40px;
    }

    .original-title {
        font-style: italic;
        font-size: 20px;
    }

    .release-date {
        font-size: 20px;
    }

    .description {
        font-size: 18px;
    }
    .description::before {
        content: 'Description: ';
    }
    .cont {
        display: flex;
        margin: auto;
    }
    .info-div {
        margin-left: 20px;
    }
    .score {
        display: inline-block;
        line-height: 0px;
        border-radius: 50%;
        border: 2px solid;
        font-size: 32px;
        border-color: white;
    }

    .score span {
        display: inline-block;
        padding-top: 50%;
        padding-bottom: 50%;
        margin-left: 8px;
        margin-right: 8px;
    }
</style>


<h1>@ViewData["Title"]</h1>

<div class="cont">
    <div class="img-div">
        <img src="@Model.PosterPath" alt="movie poster" />
    </div>
    <div class="info-div">
        <span class="title"><b>@Model.Title</b></span>
        <span class="original-title">@Model.OriginalTitle</span>
        <br>
        @if (@Model.ReleaseDate is null) { <span class="release-date">Release Date: Unknown</span> }
        else { <span class="release-date">Release Date: @Model.ReleaseDate</span> }
        <br>
        @if (@Model.Score is null) { <span class="score"><span>N/R</span></span> }
        else { <span class="imdb-score"><span>@Model.Score</span></span> }

        <p class="description">@Model.Overview</p>
    </div>
</div>

src/MyMovieCollection.Presentation/Views/Movie/Movies.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "Trending Right Now";
}

<style>
    h1,
    h2,
    h3 {
        text-align: center;
    }

    img {
        border-radius: 10px;
        width: 14.2em;
        height: 21em;
    }

    span,
    h1,
    h2,
    h3 {
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    .title {
        font-size: 1em;
    }

    .list,
    .list > div {
        flex-direction: column;
        border: 2px solid dimgray;
        border-radius: 15px;
}

    .list {
        display: block;
        padding: 10px;
        padding-bottom: 25px;
    }
    .list > div {
        flex-direction: column;
        margin: 10px;
        display: inline-flex;
        width: 240px;
        height: 350px;
        margin: 5px;
        margin-bottom: 40px;

    }
    .list > div > div{
        margin: 5px;
        text-align: center;
    }
</style>

<h1>@ViewData["Title"]</h1>

@if (Model.Any<Movie>()) {
    <div class="list">
        @foreach (var movie in Model)
        {
            <div>
                <div class="img-div">
                    <a asp-action="About" asp-controller="Movie" asp-route-id="@movie.Id"><img src="@movie.PosterPath" alt="movie poster" /></a>
                </div>
                <div>
                    <span class="title"><b>@(movie.Title ?? "Unknown")</b></span>
                </div>
            </div>
        }
    </div>
}
else {
    <h3>There is no movie yet.</h3>
}

src/MyMovieCollection.Presentation/Views/Shared/_Layout.cshtml
@using System.Security.Claims;

@{
    var isAuthenticated = base.User.Identity?.IsAuthenticated ?? false;
    var userName = User.FindFirst(ClaimTypes.Name)?.Value ?? "Unknown";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyMovieCollection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyMovieCollection.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Main">MyMovieCollection</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (isAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Movies">Movies</a>
                            </li>
                        }
                        else {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Main">Main</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-2">
                        @if (!isAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="neon nav-link text-dark" asp-area="" asp-controller="Identity" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="neon nav-link text-dark" asp-area="" asp-controller="Identity" asp-action="Signup">Signup</a>
                            </li>
                        }
                        else {
                            <li class="nav-item">
                                <a class="neon nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profile">@userName</a>
                            </li>
                            <li class="nav-item">
                                <a class="neon nav-link text-dark" asp-area="" asp-controller="Identity" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyMovieCollection
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/MyMovieCollection.Presentation/Views/User/GetAll.cshtml
@model IEnumerable<User>

@{
    ViewData["Title"] = "Users";

    string? currUserId = ViewData["CurrUserId"] as string;
}

<style>
    h1,
    h2,
    h3 {
        text-align: center;
    }

    img {
        border-radius: 10px;
        width: 15em;
        height: 15em;
    }

    span,
    h1,
    h2,
    h3 {
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    .list{
        flex-direction: column;
        border: 2px solid dimgray;
        border-radius: 15px;
}

    .list {
        display: block;
        padding: 10px;
        padding-bottom: 25px;
        align-items: center;
        align-content: center;
    }
    .list > div {   
        flex-direction: column;
        margin: 10px;
        display: inline-flex;
        width: 240px;
        height: 350px;
        margin: 5px;
        margin-bottom: 40px;
        position: relative;
    }
    .list > div > div{
        margin: 5px;
        text-align: center;
    }
</style>

<h1>@ViewData["Title"]</h1>

@if (Model.Any<User>()) {
    <div class="list">
        @foreach (var user in Model)
        {
            @if(currUserId != user.Id) {
                <div>
                    <div class="img-div">
                        @if (string.IsNullOrWhiteSpace(user.ProfilePicture)) {
                            <img class="img-account-profile rounded-circle mb-2" src="~/ProfilePictures/DefaultProfilePicture.png" alt="">  
                        }
                        else {
                            <img class="img-account-profile rounded-circle mb-2" src="@user.ProfilePicture" alt="">
                        }                
                    </div>
                    <div>
                        <span><b>@(user.UserName ?? "Unknown")</b></span>
                        <br>
                        <span><b>@(user.Email ?? "Unknown")</b></span>
                        <br>
                        <span><b>@(user.PhoneNumber ?? "Unknown")</b></span>
                        <br>
                        <form>
                            <button class="btn btn-danger mt-2" type="submit" onclick="deleteUser('@user.Id')">DELETE</button>
                        </form>
                    </div>
                </div>
            }
            
        }
    </div>
}
else {
    <h3>You haven't added any movie yet.</h3>
}


<script>
    async function deleteUser(userId)
    {
        event.preventDefault();

        await fetch('/User/Delete?id=' + userId,
            {
                method: "DELETE",
                headers: {"Content-Type":"application/json"}
            })
                .then(data => {
                    window.location.href = '/Users';
                });
    }
</script>

src/MyMovieCollection.Presentation/Views/User/Profile.cshtml
@model User

@{
    ViewData["Title"] = Model.Login;
}

<h1>@ViewData["Title"]</h1>

<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Email: @Model.Email</li>
    <li class="list-group-item">Phone Number: @Model.PhoneNumber</li>
  </ul>
</div>

src/MyMovieCollection.Presentation/Views/User/Update.cshtml
@model User

@{
  ViewData["Title"] = Model.UserName;

  string UserName = string.Empty;
  string Email = string.Empty;
  string PhoneNumber = string.Empty;
}

<h1>@ViewData["Title"]</h1>

<style>
  .img-account-profile {
    height: 10rem;
  }

  .rounded-circle {
    border-radius: 50% !important;
  }

  .card {
    box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
  }

  .card .card-header {
    font-weight: 500;
  }

  .card-header:first-child {
    border-radius: 0.35rem 0.35rem 0 0;
  }

  .card-header {
    padding: 1rem 1.35rem;
    margin-bottom: 0;
    background-color: rgba(33, 40, 50, 0.03);
    border-bottom: 1px solid rgba(33, 40, 50, 0.125);
  }
</style>

<div class="container-xl px-4 mt-4">
  <hr class="mt-0 mb-4">
  <div class="row">
    <div class="col-xl-4">
      <div class="card mb-4 mb-xl-0 bg-dark">
        <div class="card-header">Profile Picture</div>
        <div class="card-body text-center">
          @if (string.IsNullOrWhiteSpace(Model.ProfilePicture))
          {
            <img class="img-account-profile rounded-circle mb-2" src="~/ProfilePictures/DefaultProfilePicture.png" alt="">
          }
          else
          {
            <img class="img-account-profile rounded-circle mb-2" src="@Model.ProfilePicture" alt="">
          }
        </div>
        <form class="text-center mb-3" enctype="multipart/form-data" accept="image/*" asp-action="UploadProfilePicture"
          asp-controller="User" method="post">
          <input class="form-control mb-3" type="file" name="file" id="file">
          <button class="btn btn-warning" type="file" name="file" id="file">Upload</button>
        </form>
      </div>
    </div>
    <div class="col-xl-8">
      <div class="card mb-4 bg-dark">
        <div class="card-header">Account Details</div>
        <div class="card-body">
          <form id="user-update-form">
            <div class="text-danger" asp-validation-summary="All"></div>

            <div class="mb-3">
              <label class="small mb-1" for="inputUsername">Username</label>
              <input asp-for="@UserName" class="form-control" id="inputUsername" type="text"
                placeholder="Enter your username" value="@Model.UserName">
            </div>
            <div class="mb-3">
              <label class="small mb-1" for="inputEmailAddress">Email address</label>
              <input asp-for="@Email" class="form-control" id="inputEmailAddress" type="email"
                placeholder="Enter your email address" value="@Model.Email">
            </div>
            <div class="mb-3">
              <label class="small mb-1" for="inputPhone">Phone number</label>
              <input asp-for="@PhoneNumber" class="form-control" id="inputPhone" type="tel"
                placeholder="Enter your phone number" value="@Model.PhoneNumber">
            </div>
            <button class="btn btn-warning justify-content-center" type="submit" onclick="updateUser()">Save
              changes</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  async function updateUser() {
    event.preventDefault();
    const form = document.getElementById('user-update-form');
    const formData = new FormData(form);
    let jsonData = {};
    for (let [key, value] of formData.entries()) {
      jsonData[key] = value;
    }

    await fetch('/User/Update/', {
      method: "PUT",
      body: JSON.stringify(jsonData),
      headers: {
        "Content-Type": "application/json"
      }
    })
      .then(data => {
        window.location.href = '/User/Update';
      });
  }
</script>

src/MyMovieCollection.Presentation/Views/User/UpdateProfile.cshtml
@model User

@{
  ViewData["Title"] = Model.UserName;

  string UserName = string.Empty;
  string Email = string.Empty;
  string PhoneNumber = string.Empty;
}

<h1>@ViewData["Title"]</h1>

<style>
  .img-account-profile {
    height: 10rem;
  }

  .rounded-circle {
    border-radius: 50% !important;
  }

  .card {
    box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
  }

  .card .card-header {
    font-weight: 500;
  }

  .card-header:first-child {
    border-radius: 0.35rem 0.35rem 0 0;
  }

  .card-header {
    padding: 1rem 1.35rem;
    margin-bottom: 0;
    background-color: rgba(33, 40, 50, 0.03);
    border-bottom: 1px solid rgba(33, 40, 50, 0.125);
  }
</style>

<div class="container-xl px-4 mt-4">
  <hr class="mt-0 mb-4">
  <div class="row">
    <div class="col-xl-4">
      <div class="card mb-4 mb-xl-0 bg-dark">
        <div class="card-header">Profile Picture</div>
        <div class="card-body text-center">
          @if (string.IsNullOrWhiteSpace(Model.ProfilePicture))
          {
            <img class="img-account-profile rounded-circle mb-2" src="~/ProfilePictures/DefaultProfilePicture.png" alt="">
          }
          else
          {
            <img class="img-account-profile rounded-circle mb-2" src="@Model.ProfilePicture" alt="">
          }
        </div>
        <form class="text-center mb-3" enctype="multipart/form-data" accept="image/*" asp-action="UploadProfilePicture"
          asp-controller="User" method="post">
          <input class="form-control mb-3" type="file" name="file" id="file">
          <button class="btn btn-warning" type="file" name="file" id="file">Upload</button>
        </form>
      </div>
    </div>
    <div class="col-xl-8">
      <div class="card mb-4 bg-dark">
        <div class="card-header">Account Details</div>
        <div class="card-body">
          <form id="user-update-form">
            <div class="text-danger" asp-validation-summary="All"></div>

            <div class="mb-3">
              <label class="small mb-1" for="inputUsername">Username</label>
              <input asp-for="@UserName" class="form-control" id="inputUsername" type="text"
                placeholder="Enter your username" value="@Model.UserName">
            </div>
            <div class="mb-3">
              <label class="small mb-1" for="inputEmailAddress">Email address</label>
              <input asp-for="@Email" class="form-control" id="inputEmailAddress" type="email"
                placeholder="Enter your email address" value="@Model.Email">
            </div>
            <div class="mb-3">
              <label class="small mb-1" for="inputPhone">Phone number</label>
              <input asp-for="@PhoneNumber" class="form-control" id="inputPhone" type="tel"
                placeholder="Enter your phone number" value="@Model.PhoneNumber">
            </div>
            <button class="btn btn-warning justify-content-center" type="submit" onclick="updateUser('@Model.Id')">Save
              changes</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  async function updateUser(id) {
    event.preventDefault();
    const form = document.getElementById('user-update-form');
    const formData = new FormData(form);
    let jsonData = {};
    for (let [key, value] of formData.entries()) {
      jsonData[key] = value;
    }

    await fetch('/User/Update/', {
      method: "PUT",
      body: JSON.stringify(jsonData),
      headers: {
        "Content-Type": "application/json"
      }
    })
      .then(data => {
        window.location.href = `/User/Profile?id=${id}`;
      });
  }
</script>

src/MyMovieCollection.Presentation/Views/User/UserMovies.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "My Movies";
}

<style>
    h1,
    h2,
    h3 {
        text-align: center;
    }

    img {
        border-radius: 10px;
        width: 14.2em;
        height: 21em;
    }

    span,
    h1,
    h2,
    h3 {
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    .title {
        font-size: 1em;
    }

    .list,
    .list > div {
        flex-direction: column;
        border: 2px solid dimgray;
        border-radius: 15px;
}

    .list {
        display: block;
        padding: 10px;
        padding-bottom: 25px;
        align-items: center;
        align-content: center;
    }
    .list > div {   
        flex-direction: column;
        margin: 10px;
        display: inline-flex;
        width: 240px;
        height: 350px;
        margin: 5px;
        margin-bottom: 40px;
        position: relative;
    }
    .list > div > div{
        margin: 5px;
        text-align: center;
    }
</style>

<h1>@ViewData["Title"]</h1>

@if (Model.Any<Movie>()) {
    <div class="list">
        @foreach (var movie in Model)
        {
            <div>
                <div class="img-div">
                    <a asp-action="About" asp-controller="Movie" asp-route-id="@movie.Id"><img src="@(movie.PosterPath ?? "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Black.png/220px-Black.png")" alt="movie poster" /></a>
                </div>
                <div>
                    <span class="title"><b>@(movie.Title ?? "Unknown")</b></span>
                </div>
            </div>
        }
    </div>
}
else {
    <h3>You haven't added any movie yet.</h3>
}

src/MyMovieCollection.Presentation/Views/User/WatchList.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "WatchList";
}

<style>
    h1,
    h2,
    h3 {
        text-align: center;
    }

    img {
        border-radius: 10px;
        width: 14.2em;
        height: 21em;
    }

    span,
    h1,
    h2,
    h3 {
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    .title {
        font-size: 1em;
    }

    .list,
    .list > div {
        flex-direction: column;
        border: 2px solid dimgray;
        border-radius: 15px;
}

    .list {
        display: block;
        padding: 10px;
        padding-bottom: 25px;
        align-items: center;
        align-content: center;
    }
    .list > div {   
        flex-direction: column;
        margin: 10px;
        display: inline-flex;
        width: 240px;
        height: 350px;
        margin: 5px;
        margin-bottom: 40px;
        position: relative;
    }
    .list > div > div{
        margin: 5px;
        text-align: center;
    }
</style>

<h1>@ViewData["Title"]</h1>

@if (Model.Any<Movie>()) {
    <div class="list">
        @foreach (var movie in Model)
        {
            <div>
                <div class="img-div">
                    <a asp-action="About" asp-controller="Movie" asp-route-id="@movie.Id"><img src="@(movie.PosterPath ?? "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Black.png/220px-Black.png")" alt="movie poster" /></a>
                </div>
                <div>
                    <span class="title"><b>@(movie.Title ?? "Unknown")</b></span>
                </div>
            </div>
        }
    </div>
}
else {
    <h3>There aren't any movies yet.</h3>
}